import type { FeaturedProduct } from '@/types/product';

/**
 * Artikkan catalogue — sourced from client product photography.
 * Homepage featured grid uses `featuredProducts`; full browse uses `catalogProducts`.
 */
export const featuredProducts = [
  {
    id: 'artk-sof-01',
    slug: 'artk-sof-01',
    nameKey: 'artk-sof-01',
    categoryKey: 'seating',
    reference: 'ARTK-SOF-01',
    image: {
      src: '/images/catalog/products/artk-sof-01.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-dt-01',
    slug: 'artk-dt-01',
    nameKey: 'artk-dt-01',
    categoryKey: 'tables',
    reference: 'ARTK-DT-01',
    image: {
      src: '/images/catalog/products/artk-dt-01.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-cot-02',
    slug: 'artk-cot-02',
    nameKey: 'artk-cot-02',
    categoryKey: 'tables',
    reference: 'ARTK-COT-02',
    image: {
      src: '/images/catalog/products/artk-cot-02.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-un-01',
    slug: 'artk-un-01',
    nameKey: 'artk-un-01',
    categoryKey: 'unit-cabinets',
    reference: 'ARTK-UN-01',
    image: {
      src: '/images/catalog/products/artk-un-01.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-ch-01-wv',
    slug: 'artk-ch-01-wv',
    nameKey: 'artk-ch-01-wv',
    categoryKey: 'seating',
    reference: 'ARTK-CH-01',
    image: {
      src: '/images/catalog/products/artk-ch-01-wv.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-ben-01',
    slug: 'artk-ben-01',
    nameKey: 'artk-ben-01',
    categoryKey: 'seating',
    reference: 'ARTK-BEN-01',
    image: {
      src: '/images/catalog/products/artk-ben-01.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-ct-01',
    slug: 'artk-ct-01',
    nameKey: 'artk-ct-01',
    categoryKey: 'tables',
    reference: 'ARTK-CT-01',
    image: {
      src: '/images/catalog/products/artk-ct-01.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-shf-01',
    slug: 'artk-shf-01',
    nameKey: 'artk-shf-01',
    categoryKey: 'home-decor',
    reference: 'ARTK-SHF-01',
    image: {
      src: '/images/catalog/products/artk-shf-01.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
] as const satisfies readonly FeaturedProduct[];

export const additionalCatalogProducts = [
  {
    id: 'candle-holder',
    slug: 'candle-holder',
    nameKey: 'candle-holder',
    categoryKey: 'accessories',
    image: {
      src: '/images/catalog/products/candle-holder.jpg',
      width: 260,
      height: 260,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'coasters',
    slug: 'coasters',
    nameKey: 'coasters',
    categoryKey: 'accessories',
    image: {
      src: '/images/catalog/products/coasters.jpg',
      width: 260,
      height: 260,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'container',
    slug: 'container',
    nameKey: 'container',
    categoryKey: 'accessories',
    image: {
      src: '/images/catalog/products/container.jpg',
      width: 260,
      height: 260,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'mobkhar',
    slug: 'mobkhar',
    nameKey: 'mobkhar',
    categoryKey: 'accessories',
    image: {
      src: '/images/catalog/products/mobkhar.jpg',
      width: 260,
      height: 260,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'napkin-holder',
    slug: 'napkin-holder',
    nameKey: 'napkin-holder',
    categoryKey: 'accessories',
    image: {
      src: '/images/catalog/products/napkin-holder.jpg',
      width: 260,
      height: 260,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'tissue-box',
    slug: 'tissue-box',
    nameKey: 'tissue-box',
    categoryKey: 'accessories',
    image: {
      src: '/images/catalog/products/tissue-box.jpg',
      width: 260,
      height: 260,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-aw-wv-01',
    slug: 'artk-aw-wv-01',
    nameKey: 'artk-aw-wv-01',
    categoryKey: 'home-decor',
    reference: 'ARTK-AW-WV-01',
    image: {
      src: '/images/catalog/products/artk-aw-wv-01.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-aw-wv-01a',
    slug: 'artk-aw-wv-01a',
    nameKey: 'artk-aw-wv-01a',
    categoryKey: 'home-decor',
    reference: 'ARTK-AW-WV-01A',
    image: {
      src: '/images/catalog/products/artk-aw-wv-01a.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-aw-wv-01b',
    slug: 'artk-aw-wv-01b',
    nameKey: 'artk-aw-wv-01b',
    categoryKey: 'home-decor',
    reference: 'ARTK-AW-WV-01B',
    image: {
      src: '/images/catalog/products/artk-aw-wv-01b.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-bst-01',
    slug: 'artk-bst-01',
    nameKey: 'artk-bst-01',
    categoryKey: 'home-decor',
    reference: 'ARTK-BST-01',
    image: {
      src: '/images/catalog/products/artk-bst-01.jpg',
      width: 300,
      height: 200,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-shf-02',
    slug: 'artk-shf-02',
    nameKey: 'artk-shf-02',
    categoryKey: 'home-decor',
    reference: 'ARTK-SHF-02',
    image: {
      src: '/images/catalog/products/artk-shf-02.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-shf-03',
    slug: 'artk-shf-03',
    nameKey: 'artk-shf-03',
    categoryKey: 'home-decor',
    reference: 'ARTK-SHF-03',
    image: {
      src: '/images/catalog/products/artk-shf-03.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-mr-wp-01',
    slug: 'artk-mr-wp-01',
    nameKey: 'artk-mr-wp-01',
    categoryKey: 'home-decor',
    reference: 'ARTK-MR-WP-01',
    image: {
      src: '/images/catalog/products/artk-mr-wp-01.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-mr-wv-01',
    slug: 'artk-mr-wv-01',
    nameKey: 'artk-mr-wv-01',
    categoryKey: 'home-decor',
    reference: 'ARTK-MR-WV-01',
    image: {
      src: '/images/catalog/products/artk-mr-wv-01.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-mr-wv-01a',
    slug: 'artk-mr-wv-01a',
    nameKey: 'artk-mr-wv-01a',
    categoryKey: 'home-decor',
    reference: 'ARTK-MR-WV-01A',
    image: {
      src: '/images/catalog/products/artk-mr-wv-01a.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-mbh-wv-01',
    slug: 'artk-mbh-wv-01',
    nameKey: 'artk-mbh-wv-01',
    categoryKey: 'home-decor',
    reference: 'ARTK-MBH-WV-01',
    image: {
      src: '/images/catalog/products/artk-mbh-wv-01.jpg',
      width: 300,
      height: 209,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-pfr-wv-01',
    slug: 'artk-pfr-wv-01',
    nameKey: 'artk-pfr-wv-01',
    categoryKey: 'home-decor',
    reference: 'ARTK-PFR-WV-01',
    image: {
      src: '/images/catalog/products/artk-pfr-wv-01.jpg',
      width: 300,
      height: 223,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-plr-wv-01',
    slug: 'artk-plr-wv-01',
    nameKey: 'artk-plr-wv-01',
    categoryKey: 'home-decor',
    reference: 'ARTK-PLR-WV-01',
    image: {
      src: '/images/catalog/products/artk-plr-wv-01.jpg',
      width: 259,
      height: 192,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-try-01',
    slug: 'artk-try-01',
    nameKey: 'artk-try-01',
    categoryKey: 'home-decor',
    reference: 'ARTK-TRY-01',
    image: {
      src: '/images/catalog/products/artk-try-01.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-ben-02',
    slug: 'artk-ben-02',
    nameKey: 'artk-ben-02',
    categoryKey: 'seating',
    reference: 'ARTK-BEN-02',
    image: {
      src: '/images/catalog/products/artk-ben-02.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-ben-03',
    slug: 'artk-ben-03',
    nameKey: 'artk-ben-03',
    categoryKey: 'seating',
    reference: 'ARTK-BEN-03',
    image: {
      src: '/images/catalog/products/artk-ben-03.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-ben-04',
    slug: 'artk-ben-04',
    nameKey: 'artk-ben-04',
    categoryKey: 'seating',
    reference: 'ARTK-BEN-04',
    image: {
      src: '/images/catalog/products/artk-ben-04.jpg',
      width: 263,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-ben-05',
    slug: 'artk-ben-05',
    nameKey: 'artk-ben-05',
    categoryKey: 'seating',
    reference: 'ARTK-BEN-05',
    image: {
      src: '/images/catalog/products/artk-ben-05.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-ch-01-wp',
    slug: 'artk-ch-01-wp',
    nameKey: 'artk-ch-01-wp',
    categoryKey: 'seating',
    reference: 'ARTK-CH-01',
    image: {
      src: '/images/catalog/products/artk-ch-01-wp.jpg',
      width: 221,
      height: 191,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-ch-02',
    slug: 'artk-ch-02',
    nameKey: 'artk-ch-02',
    categoryKey: 'seating',
    reference: 'ARTK-CH-02',
    image: {
      src: '/images/catalog/products/artk-ch-02.jpg',
      width: 253,
      height: 205,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-ch-03',
    slug: 'artk-ch-03',
    nameKey: 'artk-ch-03',
    categoryKey: 'seating',
    reference: 'ARTK-CH-03',
    image: {
      src: '/images/catalog/products/artk-ch-03.jpg',
      width: 253,
      height: 210,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-ch-04-wv',
    slug: 'artk-ch-04-wv',
    nameKey: 'artk-ch-04-wv',
    categoryKey: 'seating',
    reference: 'ARTK-CH-04',
    image: {
      src: '/images/catalog/products/artk-ch-04-wv.jpg',
      width: 223,
      height: 200,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-pof-01',
    slug: 'artk-pof-01',
    nameKey: 'artk-pof-01',
    categoryKey: 'seating',
    reference: 'ARTK-POF-01',
    image: {
      src: '/images/catalog/products/artk-pof-01.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-pof-02-wp',
    slug: 'artk-pof-02-wp',
    nameKey: 'artk-pof-02-wp',
    categoryKey: 'seating',
    reference: 'ARTK-POF-02',
    image: {
      src: '/images/catalog/products/artk-pof-02-wp.jpg',
      width: 208,
      height: 166,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-pof-02-wv',
    slug: 'artk-pof-02-wv',
    nameKey: 'artk-pof-02-wv',
    categoryKey: 'seating',
    reference: 'ARTK-POF-02',
    image: {
      src: '/images/catalog/products/artk-pof-02-wv.jpg',
      width: 200,
      height: 161,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-pof-03',
    slug: 'artk-pof-03',
    nameKey: 'artk-pof-03',
    categoryKey: 'seating',
    reference: 'ARTK-POF-03',
    image: {
      src: '/images/catalog/products/artk-pof-03.jpg',
      width: 300,
      height: 202,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-pof-04',
    slug: 'artk-pof-04',
    nameKey: 'artk-pof-04',
    categoryKey: 'seating',
    reference: 'ARTK-POF-04',
    image: {
      src: '/images/catalog/products/artk-pof-04.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-sof-02',
    slug: 'artk-sof-02',
    nameKey: 'artk-sof-02',
    categoryKey: 'seating',
    reference: 'ARTK-SOF-02',
    image: {
      src: '/images/catalog/products/artk-sof-02.jpg',
      width: 300,
      height: 200,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-sof-03',
    slug: 'artk-sof-03',
    nameKey: 'artk-sof-03',
    categoryKey: 'seating',
    reference: 'ARTK-SOF-03',
    image: {
      src: '/images/catalog/products/artk-sof-03.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-sof-04',
    slug: 'artk-sof-04',
    nameKey: 'artk-sof-04',
    categoryKey: 'seating',
    reference: 'ARTK-SOF-04',
    image: {
      src: '/images/catalog/products/artk-sof-04.jpg',
      width: 218,
      height: 159,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-sof-05',
    slug: 'artk-sof-05',
    nameKey: 'artk-sof-05',
    categoryKey: 'seating',
    reference: 'ARTK-SOF-05',
    image: {
      src: '/images/catalog/products/artk-sof-05.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-ct-02',
    slug: 'artk-ct-02',
    nameKey: 'artk-ct-02',
    categoryKey: 'tables',
    reference: 'ARTK-CT-02',
    image: {
      src: '/images/catalog/products/artk-ct-02.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-ct-03-wv',
    slug: 'artk-ct-03-wv',
    nameKey: 'artk-ct-03-wv',
    categoryKey: 'tables',
    reference: 'ARTK-CT-03',
    image: {
      src: '/images/catalog/products/artk-ct-03-wv.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-cot-01-a',
    slug: 'artk-cot-01-a',
    nameKey: 'artk-cot-01-a',
    categoryKey: 'tables',
    reference: 'ARTK-COT-01-A',
    image: {
      src: '/images/catalog/products/artk-cot-01-a.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-cot-01',
    slug: 'artk-cot-01',
    nameKey: 'artk-cot-01',
    categoryKey: 'tables',
    reference: 'ARTK-COT-01',
    image: {
      src: '/images/catalog/products/artk-cot-01.jpg',
      width: 258,
      height: 178,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-dt-02',
    slug: 'artk-dt-02',
    nameKey: 'artk-dt-02',
    categoryKey: 'tables',
    reference: 'ARTK-DT-02',
    image: {
      src: '/images/catalog/products/artk-dt-02.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-dt-03',
    slug: 'artk-dt-03',
    nameKey: 'artk-dt-03',
    categoryKey: 'tables',
    reference: 'ARTK-DT-03',
    image: {
      src: '/images/catalog/products/artk-dt-03.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-dst-01',
    slug: 'artk-dst-01',
    nameKey: 'artk-dst-01',
    categoryKey: 'tables',
    reference: 'ARTK-DST-01',
    image: {
      src: '/images/catalog/products/artk-dst-01.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-st-02-wp',
    slug: 'artk-st-02-wp',
    nameKey: 'artk-st-02-wp',
    categoryKey: 'tables',
    reference: 'ARTK-ST-02',
    image: {
      src: '/images/catalog/products/artk-st-02-wp.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-st-02-wv',
    slug: 'artk-st-02-wv',
    nameKey: 'artk-st-02-wv',
    categoryKey: 'tables',
    reference: 'ARTK-ST-02',
    image: {
      src: '/images/catalog/products/artk-st-02-wv.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-un-02-wp',
    slug: 'artk-un-02-wp',
    nameKey: 'artk-un-02-wp',
    categoryKey: 'unit-cabinets',
    reference: 'ARTK-UN-02',
    image: {
      src: '/images/catalog/products/artk-un-02-wp.jpg',
      width: 300,
      height: 227,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-un-04',
    slug: 'artk-un-04',
    nameKey: 'artk-un-04',
    categoryKey: 'unit-cabinets',
    reference: 'ARTK-UN-04',
    image: {
      src: '/images/catalog/products/artk-un-04.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
  {
    id: 'artk-un-07c',
    slug: 'artk-un-07c',
    nameKey: 'artk-un-07c',
    categoryKey: 'unit-cabinets',
    reference: 'ARTK-UN-07C',
    image: {
      src: '/images/catalog/products/artk-un-07c.jpg',
      width: 300,
      height: 217,
      fit: 'contain',
      objectPosition: 'center center',
    },
  },
] as const satisfies readonly FeaturedProduct[];

export const catalogProducts = [
  ...featuredProducts,
  ...additionalCatalogProducts,
] as const;

export function getFeaturedProductById(
  id: string,
): FeaturedProduct | undefined {
  return featuredProducts.find((product) => product.id === id);
}

export function getCatalogProductById(
  id: string,
): FeaturedProduct | undefined {
  return catalogProducts.find((product) => product.id === id);
}
